language: go
go:
  - 1.6
  - 1.7
  - 1.8
  - 1.9
sudo: false
install:
  - wget -q https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64 -O dep
  - chmod +x dep
  - ./dep ensure
script:
  - make test-coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
